// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package ie.gmit.ds;

public final class Inventory {
  private Inventory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ie_gmit_ds_Hash_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ie_gmit_ds_Hash_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ie_gmit_ds_HashResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ie_gmit_ds_HashResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ie_gmit_ds_Validate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ie_gmit_ds_Validate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inventory.proto\022\nie.gmit.ds\032\036google/pr" +
      "otobuf/wrappers.proto\032\033google/protobuf/e" +
      "mpty.proto\"(\n\004Hash\022\016\n\006userId\030\001 \001(\005\022\020\n\010pa" +
      "ssword\030\002 \001(\t\"B\n\014HashResponse\022\016\n\006userId\030\001" +
      " \001(\005\022\024\n\014hashPassword\030\002 \001(\014\022\014\n\004salt\030\003 \001(\014" +
      "\"B\n\010Validate\022\020\n\010password\030\001 \001(\t\022\026\n\016hashed" +
      "Password\030\002 \001(\014\022\014\n\004salt\030\003 \001(\0142\204\001\n\020Invento" +
      "ryService\0222\n\004hash\022\020.ie.gmit.ds.Hash\032\030.ie" +
      ".gmit.ds.HashResponse\022<\n\010validate\022\024.ie.g" +
      "mit.ds.Validate\032\032.google.protobuf.BoolVa" +
      "lueB\016\n\nie.gmit.dsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_ie_gmit_ds_Hash_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ie_gmit_ds_Hash_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ie_gmit_ds_Hash_descriptor,
        new java.lang.String[] { "UserId", "Password", });
    internal_static_ie_gmit_ds_HashResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ie_gmit_ds_HashResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ie_gmit_ds_HashResponse_descriptor,
        new java.lang.String[] { "UserId", "HashPassword", "Salt", });
    internal_static_ie_gmit_ds_Validate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ie_gmit_ds_Validate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ie_gmit_ds_Validate_descriptor,
        new java.lang.String[] { "Password", "HashedPassword", "Salt", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
